/* CREACIÓN DE SOCIOS */
	
INSERT INTO APP.SOCIOS (ID, FECHAALTA, FECHABAJA, APELLIDO, CERTIFICADO, CODPOSTAL, CORREO, DIRECCION, ESTADO, NOMBRE, OBSERVACIONES, POBLACION, PROVINCIA, SECTOR, TELEFONO, APADR_CODAPADRINAMIENTO, USUARIO_USUARIO) 
	VALUES (1, CURRENT_DATE, CURRENT_DATE, 'Martinez', NULL, NULL, 'socio@acoes.es', NULL, NULL, 'Socio', NULL, NULL, NULL, NULL, NULL, NULL, 'socio')
INSERT INTO APP.SOCIOS (ID, FECHAALTA, FECHABAJA, APELLIDO, CERTIFICADO, CODPOSTAL, CORREO, DIRECCION, ESTADO, NOMBRE, OBSERVACIONES, POBLACION, PROVINCIA, SECTOR, TELEFONO, APADR_CODAPADRINAMIENTO, USUARIO_USUARIO) 
	VALUES (2, CURRENT_DATE, CURRENT_DATE, 'Montañez', NULL, NULL, 'socio2@acoes.es', NULL, NULL, 'Socio2', NULL, NULL, NULL, NULL, NULL, NULL, NULL)

/* CREACIÓN DE UN USUARIO ADMINISTRADOR Y OTRO SOCIO */
INSERT INTO APP.USUARIO (USUARIO, APELLIDOS, EMAIL, PASS, ROL, SOCIO_ID) 
	VALUES ('admin', 'apellido1', 'admin@acoes.es', 'pass', 1, NULL)
INSERT INTO APP.USUARIO (USUARIO, APELLIDOS, EMAIL, PASS, ROL, SOCIO_ID) 
	VALUES ('socio', 'apellido2', 'socio@acoes.es', 'pass', 0, NULL)
	
/* CREACIÓN DE CUOTAS DE PRUEBA */

INSERT INTO APP.CUOTA (CODIGOCUOTA, "APORTACIÓN", NOMBRECUOTA, TIPO) 
	VALUES (1, 5.0, 'Nombre cuota', 'Donación mensual')
INSERT INTO APP.CUOTA (CODIGOCUOTA, "APORTACIÓN", NOMBRECUOTA, TIPO) 
	VALUES (2, 5.75, 'Nombre2Cuota', 'Apadrinamiento')

/* CREACIÓN DE NIÑOS */

INSERT INTO APP.NINOS (ID, AGENTE, APELLIDOS, BECA, COLONIAACTUAL, COMUNIDADPROCEDENCIA, ESTADO, FECHAALTA, FECHABAJA, FECHANAC, FOTO, GRADOCURSO, NOMBRE, OBSERVACIONES, PROYECTO, SEXO, CODAPADRINAMIENTO_CODAPADRINAMIENTO) 
	VALUES (1, NULL, 'Apellido1', NULL, 'Mancara', 'Caruca', 'Activo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, '3', 'Mateo', NULL, NULL, 'Varón', NULL)
INSERT INTO APP.NINOS (ID, AGENTE, APELLIDOS, BECA, COLONIAACTUAL, COMUNIDADPROCEDENCIA, ESTADO, FECHAALTA, FECHABAJA, FECHANAC, FOTO, GRADOCURSO, NOMBRE, OBSERVACIONES, PROYECTO, SEXO, CODAPADRINAMIENTO_CODAPADRINAMIENTO) 
	VALUES (2, NULL, 'Apellido2', NULL, 'Cacaruca', 'Samancara', 'Activo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, '1', 'Luks', NULL, NULL, 'Varón', NULL)


/* CREACIÓN DE APADRINAMIENTOS */

INSERT INTO APP.APADRINAMIENTO (CODAPADRINAMIENTO, FECHAAPADRINAMIENTO, OBSERVACIONES, NUMSOCIO_ID, CODNINO_ID) 
	VALUES (1, CURRENT_TIMESTAMP, NULL, 1, 1)


/* CREACIÓN DE ENVÍOS */

INSERT INTO APP.ENVIO (CODENVIO, FECHAENVIO, FECHALLEGADA, OBSERVACIONES, CODAPADRINAMIENTO_CODAPADRINAMIENTO) 
	VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1)
INSERT INTO APP.APADRINAMIENTO_ENVIO (APADRINAMIENTO_CODAPADRINAMIENTO, CODENVIO_CODENVIO) 
	VALUES (1, 1)
